# Generated by Django 3.0.7 on 2020-06-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='aucun', max_length=50, null=True)),
                ('year_from_bac', models.SmallIntegerField(default=0, help_text='year since bac', null=True, verbose_name='year')),
                ('scholar_year', models.CharField(default='0000-00001', max_length=9, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='comment',
            field=models.CharField(blank=True, default='', help_text='some comment abount the student', max_length=255, verbose_name='comments'),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='x@y.z', help_text='mail of thee student', max_length=255, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='???', help_text='last name of student', max_length=255, verbose_name='lastname'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='0999999999', help_text='phone number of the student', max_length=10, verbose_name='phonenumber'),
        ),
    ]
