# Generated by Django 3.0.7 on 2020-08-15 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0004_presence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='date',
            field=models.DateField(default='AAAA-MM-DD'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='start_time',
            field=models.TimeField(default='HH:MM:SS'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='stop_time',
            field=models.TimeField(default='HH:MM:SS'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default='AAAA-MM-DD', verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='John', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='DOE', help_text='last name of student', max_length=255, verbose_name='lastname'),
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isMissing', models.BooleanField(null=True)),
                ('date', models.DateField(default='AAAA-MM-DD')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lycee.Student')),
            ],
        ),
    ]
