# Generated by Django 3.0.7 on 2020-08-19 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0005_auto_20200815_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creneaux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField(default='HH:MM:SS')),
                ('stop_time', models.TimeField(default='HH:MM:SS')),
            ],
        ),
        migrations.AlterField(
            model_name='call',
            name='isMissing',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='creneaux',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lycee.Creneaux'),
        ),
    ]
